export const QUICK_SERVICES = [
  "plumber",
  "roofer",
  "electrician",
  "HVAC contractor",
  "dentist",
  "law firm",
  "real estate agency",
  "auto repair",
  "landscaper",
  "pest control",
  "cleaning service",
  "moving company",
  "general contractor",
  "home builder",
  "painter",
  "flooring contractor",
  "garage door repair",
  "locksmith",
  "tree service",
  "pool cleaning",
  "solar installer",
  "insurance agency",
  "accountant",
  "chiropractor",
  "med spa",
  "restaurant",
  "web design agency",
  "digital marketing agency",
  "property management",
  "carpet cleaning",
];

export const QUICK_COUNTRIES = [
  {
    code: "US",
    label: "United States",
    short: "USA",
    querySuffix: "USA",
    cities: [
      "New York NY", "Los Angeles CA", "Chicago IL", "Houston TX", "Phoenix AZ", "Philadelphia PA", "San Antonio TX", "San Diego CA", "Dallas TX", "San Jose CA",
      "Austin TX", "Jacksonville FL", "Fort Worth TX", "Columbus OH", "Charlotte NC", "San Francisco CA", "Indianapolis IN", "Seattle WA", "Denver CO", "Washington DC",
      "Boston MA", "El Paso TX", "Nashville TN", "Detroit MI", "Oklahoma City OK", "Portland OR", "Las Vegas NV", "Memphis TN", "Louisville KY", "Baltimore MD",
      "Milwaukee WI", "Albuquerque NM", "Tucson AZ", "Fresno CA", "Sacramento CA", "Mesa AZ", "Kansas City MO", "Atlanta GA", "Omaha NE", "Colorado Springs CO",
      "Raleigh NC", "Miami FL", "Virginia Beach VA", "Oakland CA", "Minneapolis MN", "Tulsa OK", "Arlington TX", "Tampa FL", "New Orleans LA", "Wichita KS",
      "Cleveland OH", "Bakersfield CA", "Aurora CO", "Anaheim CA", "Honolulu HI", "Santa Ana CA", "Riverside CA", "Corpus Christi TX", "Lexington KY", "Henderson NV",
      "Stockton CA", "Saint Paul MN", "Cincinnati OH", "St. Louis MO", "Pittsburgh PA", "Greensboro NC", "Lincoln NE", "Anchorage AK", "Plano TX", "Orlando FL",
    ],
  },
  {
    code: "CA",
    label: "Canada",
    short: "Canada",
    querySuffix: "Canada",
    cities: [
      "Toronto ON", "Montreal QC", "Vancouver BC", "Calgary AB", "Edmonton AB", "Ottawa ON", "Winnipeg MB", "Quebec City QC", "Hamilton ON", "Kitchener ON",
      "London ON", "Victoria BC", "Halifax NS", "Oshawa ON", "Windsor ON", "Saskatoon SK", "Regina SK", "St. Catharines ON", "Kelowna BC", "Barrie ON",
      "Sherbrooke QC", "Guelph ON", "Abbotsford BC", "Kingston ON", "Kanata ON", "Trois-Rivieres QC", "Moncton NB", "Milton ON", "Red Deer AB", "Brantford ON",
      "Thunder Bay ON", "White Rock BC", "Nanaimo BC", "Lethbridge AB", "Kamloops BC", "Peterborough ON", "Saint John NB", "Chilliwack BC", "Sarnia ON", "Sudbury ON",
      "Drummondville QC", "Prince George BC", "Sault Ste. Marie ON", "Medicine Hat AB", "North Bay ON", "Fredericton NB", "Granby QC", "Belleville ON", "Charlottetown PE", "Chatham ON",
      "Vernon BC", "Cornwall ON", "Courtenay BC", "Rimouski QC", "Wood Buffalo AB", "Beloeil QC", "Spruce Grove AB", "Brandon MB", "Joliette QC", "Welland ON",
      "Saint-Hyacinthe QC", "Lloydminster AB", "Penticton BC", "Campbell River BC", "Moose Jaw SK", "Leamington ON", "Stratford ON", "Orillia ON", "Timmins ON", "Prince Albert SK",
    ],
  },
  {
    code: "AU",
    label: "Australia",
    short: "Australia",
    querySuffix: "Australia",
    cities: [
      "Sydney NSW", "Melbourne VIC", "Brisbane QLD", "Perth WA", "Adelaide SA", "Gold Coast QLD", "Canberra ACT", "Newcastle NSW", "Wollongong NSW", "Logan City QLD",
      "Geelong VIC", "Hobart TAS", "Townsville QLD", "Cairns QLD", "Darwin NT", "Toowoomba QLD", "Ballarat VIC", "Bendigo VIC", "Albury NSW", "Launceston TAS",
      "Mackay QLD", "Rockhampton QLD", "Bunbury WA", "Coffs Harbour NSW", "Bundaberg QLD", "Wagga Wagga NSW", "Hervey Bay QLD", "Shepparton VIC", "Mildura VIC", "Port Macquarie NSW",
      "Gladstone QLD", "Tamworth NSW", "Traralgon VIC", "Orange NSW", "Dubbo NSW", "Geraldton WA", "Bathurst NSW", "Warrnambool VIC", "Nowra NSW", "Albany WA",
      "Kalgoorlie WA", "Devonport TAS", "Mount Gambier SA", "Lismore NSW", "Nelson Bay NSW", "Maryborough QLD", "Alice Springs NT", "Taree NSW", "Ballina NSW", "Armidale NSW",
      "Goulburn NSW", "Whyalla SA", "Echuca VIC", "Forster NSW", "Karratha WA", "Burnie TAS", "Broken Hill NSW", "Ulladulla NSW", "Busselton WA", "Horsham VIC",
      "Kempsey NSW", "Port Lincoln SA", "Sale VIC", "Muswellbrook NSW", "Swan Hill VIC", "Warwick QLD", "Mudgee NSW", "Lithgow NSW", "Emerald QLD", "Broome WA",
    ],
  },
  {
    code: "DE",
    label: "Germany",
    short: "Germany",
    querySuffix: "Germany",
    cities: [
      "Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Dusseldorf", "Leipzig", "Dortmund", "Essen",
      "Bremen", "Dresden", "Hanover", "Nuremberg", "Duisburg", "Bochum", "Wuppertal", "Bielefeld", "Bonn", "Munster",
      "Karlsruhe", "Mannheim", "Augsburg", "Wiesbaden", "Gelsenkirchen", "Monchengladbach", "Braunschweig", "Chemnitz", "Kiel", "Aachen",
      "Halle", "Magdeburg", "Freiburg", "Krefeld", "Lubeck", "Oberhausen", "Erfurt", "Mainz", "Rostock", "Kassel",
      "Hagen", "Hamm", "Saarbrucken", "Mulheim", "Potsdam", "Ludwigshafen", "Oldenburg", "Leverkusen", "Osnabruck", "Solingen",
      "Heidelberg", "Herne", "Neuss", "Darmstadt", "Paderborn", "Regensburg", "Ingolstadt", "Wurzburg", "Furth", "Wolfsburg",
      "Offenbach", "Ulm", "Heilbronn", "Pforzheim", "Gottingen", "Bottrop", "Trier", "Recklinghausen", "Reutlingen", "Bremerhaven",
    ],
  },
  {
    code: "GB",
    label: "United Kingdom",
    short: "UK",
    querySuffix: "UK",
    cities: [
      "London", "Birmingham", "Manchester", "Glasgow", "Liverpool", "Leeds", "Sheffield", "Edinburgh", "Bristol", "Cardiff",
      "Leicester", "Coventry", "Bradford", "Belfast", "Nottingham", "Hull", "Newcastle upon Tyne", "Stoke-on-Trent", "Southampton", "Derby",
      "Portsmouth", "Brighton", "Plymouth", "Northampton", "Reading", "Luton", "Wolverhampton", "Bolton", "Bournemouth", "Norwich",
      "Swindon", "Swansea", "Milton Keynes", "Southend-on-Sea", "Middlesbrough", "Sunderland", "Warrington", "Huddersfield", "Oxford", "York",
      "Slough", "Poole", "Blackpool", "Dundee", "Cambridge", "Ipswich", "Wigan", "Telford", "Gloucester", "Exeter",
      "Peterborough", "Doncaster", "Rotherham", "Maidstone", "Worcester", "Gillingham", "Basildon", "Worthing", "Derry", "Preston",
      "Chelmsford", "Newport", "Oldham", "Basingstoke", "Chatham", "Lincoln", "Chester", "Bath", "High Wycombe", "Stevenage",
    ],
  },
  {
    code: "FR",
    label: "France",
    short: "France",
    querySuffix: "France",
    cities: [
      "Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Montpellier", "Strasbourg", "Bordeaux", "Lille",
      "Rennes", "Reims", "Le Havre", "Saint-Etienne", "Toulon", "Grenoble", "Dijon", "Angers", "Nimes", "Villeurbanne",
      "Clermont-Ferrand", "Le Mans", "Aix-en-Provence", "Brest", "Tours", "Amiens", "Limoges", "Annecy", "Perpignan", "Boulogne-Billancourt",
      "Metz", "Besancon", "Orleans", "Saint-Denis", "Rouen", "Mulhouse", "Caen", "Nancy", "Argenteuil", "Montreuil",
      "Roubaix", "Tourcoing", "Nanterre", "Avignon", "Vitry-sur-Seine", "Creteil", "Poitiers", "Dunkerque", "Asnieres-sur-Seine", "Courbevoie",
      "Versailles", "Colombes", "Fort-de-France", "Aulnay-sous-Bois", "Saint-Pierre", "Rueil-Malmaison", "Pau", "Aubervilliers", "Le Tampon", "Champigny-sur-Marne",
      "Antibes", "La Rochelle", "Cannes", "Calais", "Saint-Maur-des-Fosses", "Beziers", "Bourges", "Ajaccio", "Colmar", "Quimper",
    ],
  },
  {
    code: "IN",
    label: "India",
    short: "India",
    querySuffix: "India",
    cities: [
      "Mumbai", "Delhi", "Bengaluru", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Surat", "Pune", "Jaipur",
      "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Pimpri-Chinchwad", "Patna", "Vadodara",
      "Ghaziabad", "Ludhiana", "Agra", "Nashik", "Faridabad", "Meerut", "Rajkot", "Kalyan-Dombivli", "Vasai-Virar", "Varanasi",
      "Srinagar", "Aurangabad", "Dhanbad", "Amritsar", "Navi Mumbai", "Allahabad", "Ranchi", "Howrah", "Coimbatore", "Jabalpur",
      "Gwalior", "Vijayawada", "Jodhpur", "Madurai", "Raipur", "Kota", "Guwahati", "Chandigarh", "Solapur", "Hubli-Dharwad",
      "Bareilly", "Moradabad", "Mysore", "Gurgaon", "Aligarh", "Jalandhar", "Tiruchirappalli", "Bhubaneswar", "Salem", "Warangal",
      "Mira-Bhayandar", "Thiruvananthapuram", "Guntur", "Bhiwandi", "Saharanpur", "Gorakhpur", "Bikaner", "Amravati", "Noida", "Jamshedpur",
    ],
  },
  {
    code: "ES",
    label: "Spain",
    short: "Spain",
    querySuffix: "Spain",
    cities: [
      "Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Malaga", "Murcia", "Palma", "Las Palmas", "Bilbao",
      "Alicante", "Cordoba", "Valladolid", "Vigo", "Gijon", "Hospitalet de Llobregat", "Vitoria-Gasteiz", "A Coruna", "Granada", "Elche",
      "Oviedo", "Badalona", "Cartagena", "Terrassa", "Jerez de la Frontera", "Sabadell", "Mostoles", "Santa Cruz de Tenerife", "Pamplona", "Almeria",
      "Alcala de Henares", "Fuenlabrada", "Leganes", "Donostia-San Sebastian", "Getafe", "Burgos", "Albacete", "Santander", "Castellon", "Logrono",
      "Badajoz", "Salamanca", "Huelva", "Lleida", "Tarragona", "Marbella", "Leon", "Cadiz", "Dos Hermanas", "Mataro",
      "Torrejon de Ardoz", "Parla", "Algeciras", "Santa Coloma de Gramenet", "Ourense", "Jaen", "Alcobendas", "Reus", "Telde", "Barakaldo",
      "Lugo", "Santiago de Compostela", "Girona", "Caceres", "Lorca", "Coslada", "Talavera de la Reina", "El Puerto de Santa Maria", "Cornella de Llobregat", "Aviles",
    ],
  },
  {
    code: "IT",
    label: "Italy",
    short: "Italy",
    querySuffix: "Italy",
    cities: [
      "Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania",
      "Venice", "Verona", "Messina", "Padua", "Trieste", "Brescia", "Parma", "Taranto", "Prato", "Modena",
      "Reggio Calabria", "Reggio Emilia", "Perugia", "Ravenna", "Livorno", "Cagliari", "Foggia", "Rimini", "Salerno", "Ferrara",
      "Sassari", "Latina", "Giugliano in Campania", "Monza", "Syracuse", "Pescara", "Bergamo", "Forli", "Trento", "Vicenza",
      "Terni", "Bolzano", "Novara", "Piacenza", "Ancona", "Andria", "Arezzo", "Udine", "Cesena", "Lecce",
      "Pesaro", "Barletta", "Alessandria", "La Spezia", "Pistoia", "Pisa", "Lucca", "Catanzaro", "Treviso", "Como",
      "Marsala", "Grosseto", "Varese", "Sesto San Giovanni", "Pozzuoli", "Casoria", "Cremona", "Cosenza", "Asti", "Ragusa",
    ],
  },
  {
    code: "NL",
    label: "Netherlands",
    short: "Netherlands",
    querySuffix: "Netherlands",
    cities: [
      "Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Groningen", "Tilburg", "Almere", "Breda", "Nijmegen",
      "Enschede", "Haarlem", "Arnhem", "Zaanstad", "Amersfoort", "Apeldoorn", "Den Bosch", "Hoofddorp", "Maastricht", "Leiden",
      "Dordrecht", "Zoetermeer", "Zwolle", "Deventer", "Delft", "Alkmaar", "Leeuwarden", "Sittard", "Venlo", "Hilversum",
      "Amstelveen", "Roosendaal", "Purmerend", "Oss", "Schiedam", "Spijkenisse", "Helmond", "Vlaardingen", "Almelo", "Gouda",
      "Zaandam", "Lelystad", "Alphen aan den Rijn", "Hoorn", "Velsen", "Ede", "Bergen op Zoom", "Capelle aan den IJssel", "Nieuwegein", "Assen",
      "Veenendaal", "Katwijk", "Zeist", "Den Helder", "Hardenberg", "Emmen", "Doetinchem", "Kerkrade", "Weert", "Middelburg",
      "Heerhugowaard", "Rijswijk", "Tiel", "Goes", "Barendrecht", "Heerenveen", "Beverwijk", "Dronten", "Gorinchem", "Kampen",
    ],
  },
];
